import { Poppins } from "next/font/google";
import React from "react";

const poppins = Poppins({
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  });

  import "./globals.css"
  
  export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };
  

function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} h-full min-h-screen flex justify-between flex-col`}
      >
        {children}
      </body>
    </html>
  );
}

export default RootLayout;
